[package]
name = "github-user-cli"
version = "0.1.0"
authors = ["matthew.cobbing <matthew.cobbing@perkbox.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
